### ISSUE TITLE
When supplied 0 seconds, returns empty string ''

### ISSUE THREAD

**Issue by dimkir** [binarykitchen/pretty-seconds#2]
```
var s = prettySeconds(0);

// s = ''; // is empty string
```

Expected behaviour would be to actually return `0 sec`. 

I bumped into this problem when trying to save in Amazon DynamoDB a field `{"prettySeconds" : ""}` and got error, because Dynamo doesn't allow to save empty strings.

**Comment by binarykitchen** [comment]
true. fixed and published the update.
